InClassApp/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.Models.Entities;
using Infrastructure.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Domain.Models.Dtos;

namespace InClassApp.Controllers
{
    /// <summary>
    /// Controller for group management
    /// </summary>
    [Authorize]
    public class GroupsController : Controller
    {
        private readonly ISubjectRepository _subjectRepository;
        private readonly IGroupRepository _groupRepository;
        private readonly ILecturersRepository _lecturersRepository;
        private readonly IMeetingRepository _meetingRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly IPresenceRecordRepository _presenceRecordRepository;
        private readonly UserManager<AppUser> _userManager;

        /// <summary>
        /// Groups controller constructor
        /// </summary>
        public GroupsController(ISubjectRepository subjectRepository, IGroupRepository groupRepository,
            ILecturersRepository lecturersRepository, IMeetingRepository meetingRepository, IStudentRepository studentRepository,
            IPresenceRecordRepository presenceRecordRepository, IServiceProvider serviceProvider)
        {
            _subjectRepository = subjectRepository;
            _groupRepository = groupRepository;
            _lecturersRepository = lecturersRepository;
            _meetingRepository = meetingRepository;
            _studentRepository = studentRepository;
            _presenceRecordRepository = presenceRecordRepository;
            _userManager = serviceProvider.GetRequiredService<UserManager<AppUser>>();
        }

        /// <summary>
        /// Gets view with all groups for current user
        /// </summary>
        /// <returns>Groups list view</returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var currentUserRoles = currentUser != null ? await _userManager.GetRolesAsync(currentUser) : null;
            if (currentUser == null || currentUserRoles == null)
            {
                return Unauthorized();
            }

            var groups = await _groupRepository.GetAll();
            if (currentUserRoles.Any(x => x == "Admin")) 
            {
                ViewData["CurrentRole"] = "Admin";
                return View(groups);
            }

            if (currentUserRoles.Any(x => x == "Lecturer"))
            {
                var currentLecturer = await _lecturersRepository.GetLecturerByUserId(currentUser.Id);
                groups = groups.Where(x => x.LecturerGroupRelations.Any(r => r.LecturerId == currentLecturer.Id)).ToList();

                ViewData["CurrentRole"] = "Lecturer";
            }
            else if (currentUserRoles.Any(x => x == "Student"))
            {
                var currentStudent = await _studentRepository.GetStudentByUserId(currentUser.Id);
                groups = groups.Where(x => x.StudentGroupRelations.Any(r => r.StudentId == currentStudent.Id)).ToList();

                ViewData["CurrentRole"] = "Student";
            }

            return View(groups);
        }

        /// <summary>
        /// Gets view with group details
        /// </summary>
        /// <param name="id">Group id</param>
        /// <returns>Group details view</returns>
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!(await IsCurrentUserHaveRightsToReadGroup((int)id)))
            {
                return Unauthorized();
            }
            if (await IsCurrentUserHaveRightsToEditGroup((int)id))
            {
                ViewData["Rights"] = "Edit";
            }
            else
            {
                ViewData["Rights"] = "Read";
            }

            var @group = await _groupRepository.GetById((int)id);
            if (@group == null)
            {
                return NotFound();
            }

            ViewData["Meetings"] = await _meetingRepository.GetMeetingsByGroupId((int)id);
            return View(@group);
        }

        /// <summary>
        /// Gets view with group create form
        /// </summary>
        /// <returns>Create group view</returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewData["Subjects"] = await _subjectRepository.GetAll();
            ViewData["Lecturers"] = await _lecturersRepository.GetAll();
            return View();
        }

        /// <summary>
        /// Saves given group if it is valid
        /// </summary>
        /// <param name="groupDto">Group dto to save</param>
        /// <returns>Group list view if saved successfully; otherwise showes an error message</returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, StudiesSemestr, SubjectId, LecturersIds, StartDate, EndDate")] SaveGroupDto groupDto)
        {
            if (ModelState.IsValid)
            {
                Group newGroup = new Group
                {
                    Name = groupDto.Name,
                    StartDate = groupDto.StartDate,
                    EndDate = groupDto.EndDate,
                    StudiesSemestr = groupDto.StudiesSemestr,
                    SubjectId = groupDto.SubjectId
                };
                await _groupRepository.Add(newGroup);

                foreach (var lecturerId in groupDto.LecturersIds)
                {
                    await _groupRepository.AddLecturerGroupRelation(lecturerId, newGroup.Id);
                }
                return RedirectToAction("Index");
            }


            ViewData["Subjects"] = await _subjectRepository.GetAll();
            ViewData["Lecturers"] = await _lecturersRepository.GetAll();
            return View();
        }

        /// <summary>
        /// Gets view with group edit form
        /// </summary>
        /// <param name="id">Group id</param>
        /// <returns>Edit group view</returns>
        [Authorize(Roles = "Admin, Lecturer")]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if ( !(await IsCurrentUserHaveRightsToEditGroup((int)id)) )
            {
                return Unauthorized();
            }

            var @group = await _groupRepository.GetById((int)id);
            if (@group == null)
            {
                return NotFound();
            }
            SaveGroupDto groupDto = new SaveGroupDto
            {
                Id = group.Id,
                Name = group.Name,
                StudiesSemestr = group.StudiesSemestr,
                StartDate = group.StartDate,
                EndDate = group.EndDate,
                SubjectId = group.SubjectId,
                LecturersIds = group.LecturerGroupRelations.Select(x => x.LecturerId).ToList()
            };

            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var currentUserRoles = await _userManager.GetRolesAsync(currentUser);

            ViewData["Role"] = currentUserRoles.FirstOrDefault();
            ViewData["Subjects"] = await _subjectRepository.GetAll();
            ViewData["Lecturers"] = await _lecturersRepository.GetAll();
            return View(groupDto);
        }

        /// <summary>
        /// Saves edited group if form is valid
        /// </summary>
        /// <param name="id"></param>
        /// <param name="groupDto">Group dto to save</param>
        /// <returns>Group list view if saved successfully; otherwise showes an error message</returns>
        [HttpPost]
        [Authorize(Roles = "Admin, Lecturer")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, StudiesSemestr, SubjectId, LecturersIds, StartDate, EndDate")] SaveGroupDto groupDto)
        {
            if (id != groupDto.Id)
            {
                return NotFound();
            }

            if (!(await IsCurrentUserHaveRightsToEditGroup(id)))
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                    var currentUserRoles = await _userManager.GetRolesAsync(currentUser);
                    var role = currentUserRoles.FirstOrDefault();

                    var group = await _groupRepository.GetById(id);
                    group.Name = groupDto.Name;
                    group.StudiesSemestr = groupDto.StudiesSemestr;
                    group.StartDate = groupDto.StartDate;
                    group.EndDate = groupDto.EndDate;
                    if(role == "Admin")
                    {
                        var currentLecturerIds = group.LecturerGroupRelations.Select(x => x.LecturerId).ToList();
                        await DeltaGroupLecturerRelations(id, currentLecturerIds, groupDto.LecturersIds);
                        group.SubjectId = groupDto.SubjectId;
                        
                    }

                    await _groupRepository.Update(group);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await GroupExists(groupDto.Id)))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

InClassApp/Controllers/PresenceRecordsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Domain.Models.Entities;
using Infrastructure.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace InClassApp.Controllers
{
    /// <summary>
    /// Controller for presence records management
    /// </summary>
    [Authorize(Roles = "Admin, Lecturer")]
    public class PresenceRecordsController : Controller
    {
        private readonly IPresenceRecordRepository _presenceRecordRepository;

        /// <summary>
        /// Presence records controller constructor
        /// </summary>
        public PresenceRecordsController(IPresenceRecordRepository presenceRecordRepository)
        {
            _presenceRecordRepository = presenceRecordRepository;
        }

        /// <summary>
        /// Gets view with the presence record details
        /// </summary>
        /// <param name="id">Presence record id</param>
        /// <returns>Presence record details view</returns>
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var presenceRecord = await _presenceRecordRepository.GetById((int)id);
            if (presenceRecord == null)
            {
                return NotFound();
            }

            return View(presenceRecord);
        }

        /// <summary>
        /// Gets view with presence record edit form
        /// </summary>
        /// <param name="id">Presence record id</param>
        /// <returns>Edit Presence record view</returns>
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var presenceRecord = await _presenceRecordRepository.GetById((int)id);
            if (presenceRecord == null)
            {
                return NotFound();
            }

            return View(presenceRecord);
        }

        /// <summary>
        /// Saves edited group if form is valid
        /// </summary>
        /// <param name="id">Presence record id</param>
        /// <param name="presenceRecord">Presence record to save</param>
        /// <returns>Meeting details view if saved successfully; otherwise showes an error message</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Status,Id")] PresenceRecord presenceRecord)
        {
            if (id != presenceRecord.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentRecord = await _presenceRecordRepository.GetByIdAsNoTracking(id);
                    presenceRecord.MeetingId = currentRecord.MeetingId;
                    presenceRecord.StudentId = currentRecord.StudentId;

                    await _presenceRecordRepository.Update(presenceRecord);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await PresenceRecordExists(presenceRecord.Id)))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Meetings", new { id = presenceRecord.MeetingId });
            }
      
            return View(presenceRecord);
        }

        private async Task<bool> PresenceRecordExists(int id)
        {
            var presenceRecords = await _presenceRecordRepository.GetAll();
            return presenceRecords.Any(e => e.Id == id);
        }
    }
}

InClassApp/Views/Meetins/AttendanceCheck.cshtml
@model Domain.Models.Entities.Meeting

@{
    ViewData["Title"] = "StartTimer";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/Meeting/meeting-attendance-check.css" />
}

<div>
    <a asp-action="Details" asp-route-id="@Model.Id" data-toggle="tooltip" data-placement="top" title="Back">
        <i class="bi bi-arrow-left-circle-fill back-action"></i>
    </a>
</div>

<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <div class="center bordered">
            <span id="code-text" class="code-text">@ViewBag.DecryptedCode</span>
        </div>
        <button class="btn btn-secondary float-right mt-3" onclick="copyText()">Copy</button>
    </div>
    <div class="col-2"></div>
</div>
<div class="center">
    <a href="#" class="btn btn-danger btn-lg" onclick="StopCheck()">
        Stop
    </a>
</div>

@section scripts
{
    <script>
        function copyText() {
            let element = document.getElementById("code-text");

            navigator.clipboard.writeText(element.textContent);
        }

        function StopCheck() {
            $.ajax({
                type: "POST",
                url: "../../Meetings/AttendanceCheck",
                data: { meetingId: @Model.Id, checkValue: false },
                success: function () {
                    window.location = '../../Meetings/Details/@Model.Id';
                }
            })
        }
    </script>
}

InClassApp/Views/Meetins/Create.cshtml
@model Domain.Models.Entities.Meeting

@{
    ViewData["Title"] = "Create";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/Meeting/meeting-add.css" />
}

<div>
    <a asp-controller="Groups" asp-action="Details" asp-route-id="@ViewBag.GroupId" data-toggle="tooltip" data-placement="top" title="Back">
        <i class="bi bi-arrow-left-circle-fill back-action"></i>
    </a>
</div>

<h1>Create meeting</h1>

<hr />
<div class="row">
    <div class="col-2"></div>
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeetingStartDate" class="control-label meeting-add-label"></label>
                <input asp-for="MeetingStartDate" class="form-control" />
                <span asp-validation-for="MeetingStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeetingEndDate" class="control-label meeting-add-label"></label>
                <input asp-for="MeetingEndDate" class="form-control" />
                <span asp-validation-for="MeetingEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary float-right" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InClassApp/Views/Meetins/Delete.cshtml
@model Domain.Models.Entities.Meeting

@{
    ViewData["Title"] = "Delete";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/Meeting/meeting-delete.css" />
}

<div>
    <a asp-controller="Groups" asp-action="Details" asp-route-id="@Model.GroupId" data-toggle="tooltip" data-placement="top" title="Back">
        <i class="bi bi-arrow-left-circle-fill back-action"></i>
    </a>
</div>

<h1>Delete meeting</h1>

<div class="row">
    <div class="col-8">
        <h3>Are you sure you want to delete this meeting?</h3>
    </div>
    <div class="col-2"></div>
    <span class="group-delete-btn">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    </span>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingStartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeetingStartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingEndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeetingEndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Group.Name)
        </dd>
    </dl>
</div>

InClassApp/Views/Meetins/Details.cshtml
@model Domain.Models.Entities.Meeting

@{
    ViewData["Title"] = "Details";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/Meeting/meeting-details.css" />
}

<div>
    <a asp-controller="Groups" asp-action="Details" asp-route-id="@Model.GroupId" data-toggle="tooltip" data-placement="top" title="Back">
        <i class="bi bi-arrow-left-circle-fill back-action"></i>
    </a>
</div>

<div class="row">
    <div class="col-10">
        <span class="details-header">Meetings details</span>
        <a asp-action="Edit" asp-route-id="@Model.Id" data-toggle="tooltip" data-placement="top" title="Edit">
            <i class="bi bi-pencil-fill meeting-edit-icon"></i>
        </a>
    </div>
    <div class="col-2">
        @if (Model.IsAttendanceCheckLaunched)
        {
            <a href="#" class="btn btn-danger check-state-change-btn" onclick="CheckRealesed()">
                Stop checking
            </a>
        }
        else
        {
            <a href="#" class="btn btn-success check-state-change-btn" onclick="OpenStartCheckModel()">
                Start checking
            </a>
        }
    </div>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingStartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeetingStartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingEndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeetingEndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Group.Name)
        </dd>
    </dl>
</div>

<div class="modal fade" id="checkModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Start attendance check</h3>
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body">
                <h5>Do you really want to start attendance check?</h5>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
                <a href="#" class="btn btn-success" onclick="CheckRealesed()">Confirm</a>
            </div>
        </div>
    </div>
</div>
@if (Model.IsAttendanceCheckLaunched)
{
    <a href="#" class="btn btn-info" onclick="OpenCodeModal()">
        Show code
    </a>
}

<div class="modal fade" id="codeModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">View code</h3>
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body">
                <h2 style="float: left" id="code-text">@ViewBag.DecryptedCode</h2>
                <button class="btn btn-secondary float-right mt-3" style="float: right" onclick="copyText()">Copy</button>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>

<h4 class="mt-4">Students</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Index
            </th>
            <th>
                Status
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.Records)
        {
            <tr>
                <td>
                    @item.Student.User.UserName
                </td>
                <td>
                    @item.Student.Index
                </td>
                <td>
                    @(item.Status ? "Present" : "Absent")
                </td>
                <td>
                    <div class="records-list-actions">
                        <a asp-controller="PresenceRecords" asp-action="Details" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="top" title="Details">
                            <i class="bi bi-card-list"></i>
                        </a>
                        <a asp-controller="PresenceRecords" asp-action="Edit" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="top" title="Edit">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts
{
    <script>
        var OpenStartCheckModel = function () {
            $("#checkModal").modal('show');
        }

        var OpenCodeModal = function () {
            $("#codeModal").modal('show');
        }

        var CheckRealesed = function () {
            let shouldCheck = "@(!Model.IsAttendanceCheckLaunched)";
            $.ajax({
                type: "POST",
                url: "../../Meetings/AttendanceCheck",
                data: { meetingId: @Model.Id, checkValue: shouldCheck },
                success: function () {
                    $("#checkModal").modal('hide');
                    if ("@Model.IsAttendanceCheckLaunched" === "False") {
                        window.location = '../../Meetings/AttendanceCheck/@Model.Id';
                    }
                    else {
                        window.location = '../../Meetings/Details/@Model.Id';
                    }
                }
            })
        }

        var copyText = function() {
            let element = document.getElementById("code-text");

            navigator.clipboard.writeText(element.textContent);
        }
    </script>
}

InClassApp/Views/Meetins/DetailsStudent.cshtml
@model Domain.Models.Entities.Meeting

@{
    ViewData["Title"] = "DetailsStudent";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/Meeting/meeting-details-student.css" />
}

<div>
    <a asp-controller="Groups" asp-action="Details" asp-route-id="@Model.GroupId" data-toggle="tooltip" data-placement="top" title="Back">
        <i class="bi bi-arrow-left-circle-fill back-action"></i>
    </a>
</div>

<div class="row">
    <div class="col-10">
        <span class="details-header">Meetings details</span>
    </div>
    <div class="col-2">
        @if (Model.IsAttendanceCheckLaunched && !ViewBag.CurrentUserStatus)
        {
            <a href="#" class="btn btn-success" onclick="OpenCodeProvideModal()">
                Declare attendance
            </a>
        }
    </div>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingStartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeetingStartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingEndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeetingEndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Group.Name)
        </dd>
        <dt class="col-sm-2">
            <span>My attendance status</span>
        </dt>
        <dd class="col-sm-10">
            @(ViewBag.CurrentUserStatus ? "Present" : "Absent")
        </dd>
    </dl>
</div>

<div class="modal fade" id="inputCodeModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Provide code given by lecturer</h3>
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body">
                <h5>Code:</h5>
                <input type="text" id="providedCode">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
                <a href="#" class="btn btn-success" onclick="CodeProvidedConfirm()">Confirm</a>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        var OpenCodeProvideModal = function () {
            $("#inputCodeModal").modal('show');
        }

        var CodeProvidedConfirm = function () {
            let providedCode = $("#providedCode").val();
            $.ajax({
                type: "POST",
                url: "../../Meetings/ValidateCode",
                data: { meetingId: @Model.Id, providedCode: providedCode },
                success: function (result) {
                    if (result) {
                        $("#inputCodeModal").modal('hide');
                        location.reload(true);
                    }
                    else {
                        alert('Wrong code');
                    }
                }
            })
        }
    </script>
}

InClassApp/Views/Meetins/Edit.cshtml
@model Domain.Models.Entities.Meeting

@{
    ViewData["Title"] = "Edit";
}

@section Styles
{
    <link rel="stylesheet" href="~/css/Meeting/meeting-edit.css" />
}

<div>
    <a asp-controller="Groups" asp-action="Details" asp-route-id="@ViewBag.GroupId" data-toggle="tooltip" data-placement="top" title="Back">
        <i class="bi bi-arrow-left-circle-fill back-action"></i>
    </a>
</div>

<h1>Meeting edit</h1>

<hr />
<div class="row">
    <div class="col-2"></div>
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeetingStartDate" class="control-label meeting-edit-label"></label>
                <input asp-for="MeetingStartDate" class="form-control" />
                <span asp-validation-for="MeetingStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeetingEndDate" class="control-label meeting-edit-label"></label>
                <input asp-for="MeetingEndDate" class="form-control" />
                <span asp-validation-for="MeetingEndDate" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary float-right" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}